# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 346)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Ui/../Svg/icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.showLog = QtWidgets.QTextBrowser(self.centralwidget)
        self.showLog.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.showLog.setObjectName("showLog")
        self.gridLayout.addWidget(self.showLog, 1, 1, 1, 1)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.gridLayout.addWidget(self.verticalScrollBar, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.pushButtonToDownload = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonToDownload.setObjectName("pushButtonToDownload")
        self.verticalLayout_3.addWidget(self.pushButtonToDownload)
        self.writeLinkToPlay = QtWidgets.QLineEdit(self.centralwidget)
        self.writeLinkToPlay.setObjectName("writeLinkToPlay")
        self.verticalLayout_3.addWidget(self.writeLinkToPlay)
        self.pushButtonToPlay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonToPlay.setObjectName("pushButtonToPlay")
        self.verticalLayout_3.addWidget(self.pushButtonToPlay)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Yams - YandexMusic Client"))
        self.label.setText(_translate("MainWindow", "                                                                 Логи"))
        self.pushButtonToDownload.setText(_translate("MainWindow", "Скачать"))
        self.writeLinkToPlay.setText(_translate("MainWindow", "Введи ссылку на трек или плейлист"))
        self.pushButtonToPlay.setText(_translate("MainWindow", "Играть трек"))
