name: Build Appimage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls -al
      - uses: AppImageCrafters/build-appimage@master
        with:
          recipe: "./AppImageBuilder.yml"
        env:
          UPDATE_INFO: gh-releases-zsync|KirMozor|Yamux|latest|*x86_64.AppImage.zsync
          
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: './*.AppImage*'
