name: Build Appimage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          git clone https://github.com/KirMozor/Yamux.git
          ls -al ./Yamux
      - uses: AppImageCrafters/build-appimage@master
        env:
          UPDATE_INFO: gh-releases-zsync|KirMozor|Yamux|latest|*x86_64.AppImage.zsync
        with:
          recipe: "./Yamux/AppImageBuild/AppImageBuilder.yml"
          
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: './*.AppImage*'
